home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
]

ppw_kenta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story_1/', include('story_1.urls')),
    path('story_2/', include('story_2.urls')),
    path('story_3/', include('story_3.urls')),
    path('story_4/', include('story_4.urls')),
    path('story_5/', include('story_5.urls')),
    path('story_6/', include('story_6.urls')),
    path('story_7/', include('story_7.urls')),
    path('story_8/', include('story_8.urls')),
    path('story_9/', include('story_9.urls')),
]

story_5/urls.py
from django.urls import path

from . import views

app_name = 'story_5'

urlpatterns = [
    path('', views.index, name='story_5'),
    path('input/', views.input, name='story_5_input'),
    path('matkul/', views.matkul, name='story_5_matkul'),
    path('delete/<str:pk>', views.delete_matkul, name='story_5_delete_matkul'),
    path('edit/<str:pk>', views.edit_matkul, name='story_5_edit_matkul'),
    path('detail/<str:pk>', views.detail_matkul, name='story_5_detail_matkul'),
]

story_5/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
class MatKul(models.Model):
    SEMESTERS = [
        ('1', 'Odd'),
        ('2', 'Even'),
    ]

    YEARS = [
        (2019, '2019/2020'),
        (2020, '2020/2021'),
        (2021, '2021/2022'),
        (2022, '2022/2023'),
    ]
    UNKNOWN = '?'
    DIFFICULTIES = [
        (UNKNOWN, '❓ ???'),
        ('1', '✔️ EZ'),
        ('2', '😐 Fair'),
        ('3', '💥 Tough'),
    ]
    id = models.AutoField(primary_key=True)

    name = models.CharField(max_length=64)
    lecturer = models.CharField(max_length=100)
    classroom = models.CharField(max_length=64)
    semester = models.TextField(choices=SEMESTERS, default='1')
    year = models.IntegerField(choices=YEARS, default=2019)
    sks = models.PositiveIntegerField(validators=[MaxValueValidator(100)], default=1)
    difficulty = models.TextField(choices=DIFFICULTIES, default=UNKNOWN)
    desc = models.TextField()

story_5/forms.py
from django import forms
from story_5.models import MatKul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = MatKul
        fields = "__all__"
    

story_5/views.py
from django.shortcuts import render
from story_5.forms import MatkulForm
from story_5.models import MatKul
from django.shortcuts import HttpResponseRedirect


# Create your views here.
def index(request):
    return render(request, 'story_5/index.html', {'caption':'Story 5'})

def input(request):
    context = {}
    context['caption'] = "Story 5 Input"
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/story_5/matkul')
    else:
        form = MatkulForm()
    context['form'] = form
    return render(request, 'story_5/input.html', context)

def matkul(request):
    context = {}
    context['caption'] = "Story 5 MatKul"

    data = MatKul.objects.all()
    context['data'] = data
    return render(request, 'story_5/matkul.html', context)

def delete_matkul(request, pk):
    matkul = MatKul.objects.get(id=pk)
    if request.method == 'POST':
        matkul.delete()
        return HttpResponseRedirect('/story_5/matkul')
    else:
        pass
    return HttpResponseRedirect('/story_5/matkul')

def edit_matkul(request, pk):
    context = {}
    context['caption'] = "Story 5 Input"

    matkul = MatKul.objects.get(id=pk)
    form = MatkulForm(instance=matkul)
    if request.method == 'POST':
        form = MatkulForm(request.POST, instance=matkul)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/story_5/matkul')
    context['form'] = form
    return render(request, 'story_5/input.html', context)

def detail_matkul(request, pk):
    context = {}
    context['caption'] = "Story 5 MatKul Detail"

    datum = MatKul.objects.get(id=pk)
    context['datum'] = datum
    return render(request, 'story_5/matkul_detail.html', context)

story_5/templates/story_5/index.html
{% extends "base.html" %}
{% load static %}
{% block head_overrides %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'story_5/style.css' %}">
    <link rel="stylesheet" href="{% static 'story_2/style.css' %}">
    <title>{{caption}} - Kenta</title>
{% endblock %}
{% block content %}
    <div id="caption">{{caption}}</div>
    <div id="flexbox">
        <div class="pair">
            <a href="./input"><div class="button" id="input"></div></a>
            Input<br>Form
        </div>
        <div class="pair">
            <a href="./matkul"><div class="button" id="matkul"></div></a>
            Mata<br>Kuliah
        </div>
        <div class="pair" style="padding: 10px 0;">
            <a href="/"><div class="button" id="home"></div></a>
        </div>
    </div>
{% endblock %}

story_5/templates/story_5/input.html
{% extends "navbase.html" %}
{% load static %}
{% block head_overrides %}
    <link rel="stylesheet" href="{% static 'story_5/style.css' %}">
    <title>{{caption}} - Kenta</title>
{% endblock %}
{% block content %}
{% include './navbar.html' %}
<div class="bg">
    <div id="form-div">
        <form class="form-box" action="" method="POST" enctype="multipart/form-data">
            <h2>📚 Add Courses</h2>
            {% csrf_token %}
            <p><label for="{{form.name.id_for_label}}">Name</label>
                {{form.name}}</p>
            <p><label for="{{form.lecturer.id_for_label}}">Lecturer</label>
                {{form.lecturer}}</p>
            <div class="form-box" style="border-radius: 0%; padding:2% 1%;">
                <div><label for="{{form.classroom.id_for_label}}">Room</label>
                    {{form.classroom}}</div>
                <div><label for="{{form.semester.id_for_label}}">Term</label>
                    {{form.semester}}{{form.year}}</div>
                <div><label for="{{form.sks.id_for_label}}">Course Hours</label>
                    {{form.sks}} hour(s)</div>
                <div><label for="{{form.difficulty.id_for_label}}">Difficuty</label>
                    {{form.difficulty}}</div>
            </div>
            <p><label for="{{form.desc.id_for_label}}">Description</label>
                {{form.desc}}</p>
            <input class="form-button" id="submit-button" type="submit" value="Submit">
            <input class="form-button" id="clear-button" type="reset" value="Clear">
        </form>
    </div>
</div>
{% endblock %}

story_5/templates/story_5/matkul.html
{% extends "navbase.html" %}
{% load static %}
{% block head_overrides %}
    <link rel="stylesheet" href="{% static 'story_5/style.css' %}">
    <style>
        label {
            margin:0.5%;
            padding: 0.1rem 0.5rem;
        }

        .submit-sub {
            margin-left: 5px;
            background-repeat: no-repeat;
            background-size: 75%;
            background-position: 50% 50%;
            padding: 2px;
            border-radius: 0.2rem;
            width: 16px;
            height: 16px;
        }
        .submit-main {
            margin-left: 5px;
            background-repeat: no-repeat;
            background-size: 75%;
            background-position: 50% 50%;
            padding: 2px;
            border-radius: 0.2rem;
            width: 20px;
            height: 20px;
        }
        .submit-sub:hover, .submit-main:hover {
            cursor: pointer;
            filter: brightness(1.1);
        }
        #del {
            background-image: url("../../static/story_5/delete.svg");
            background-color:  rgb(235, 123, 103);
        }
        #edit {
            background-image: url("../../static/story_5/edit.svg");
            background-color:  rgb(226, 197, 101);
        }
        #detail {
            background-image: url("../../static/story_5/detail.svg");
            background-color:  rgb(101, 134, 226);
        }
    </style>
    <title>{{caption}} - Kenta</title>
{% endblock %}
{% block content %}
{% include './navbar.html' %}
<div class="bg">
    <div id="form-div" class="form-box">
        {% if data %}
            {% for datum in data %}
                <div class="matkul">
                    <h3>{{datum.name}}</h3>
                    <div style="margin-top: 0.5rem ;">
                        <label>{{datum.sks}} 🕒</label>
                        <label>{{datum.get_semester_display}}</label>
                        <label>{{datum.get_year_display}}</label>
                        {% if datum.difficulty == "?" %}
                            <label style="background-color: rgb(189, 151, 226);">
                        {% elif datum.difficulty == "1" %}
                            <label style="background-color: rgb(100, 197, 137);">
                        {% elif datum.difficulty == "2" %}
                            <label style="background-color: rgb(226, 214, 101);">
                        {% else %}
                            <label style="background-color: rgb(235, 123, 103);">
                        {% endif %}
                        {{datum.get_difficulty_display}}
                        </label>
                    </div>
                    <div style="display:flex; flex-direction:row-reverse;">
                        <form action='{% url "story_5:story_5_delete_matkul" datum.id %}' method="POST">
                            {% csrf_token %}
                            <input id="del" class="submit-main" type="submit" value="">
                        </form>
                        <a href='{% url "story_5:story_5_edit_matkul" datum.id %}' id="edit" class="submit-sub"></a>
                        <form action='{% url "story_5:story_5_detail_matkul" datum.id %}' method="GET">
                            <input id="detail" class="submit-main" type="submit" value="">
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

story_5/templates/story_5/matkul_detail.html
{% extends "navbase.html" %}
{% load static %}
{% block head_overrides %}
    <link rel="stylesheet" href="{% static 'story_5/style.css' %}">
    <style>
        html {
            background: transparent;
        }
        body {
            background-color: rgb(101, 134, 226);
        }
        label {
            margin:0.5%;
            padding: 0.1rem 0.5rem;
        }

        .submit-sub {
            margin-left: 5px;
            background-repeat: no-repeat;
            background-size: 75%;
            background-position: 50% 50%;
            padding: 2px;
            border-radius: 0.2rem;
            width: 16px;
            height: 16px;
        }
        .submit-main {
            margin-left: 5px;
            background-repeat: no-repeat;
            background-size: 75%;
            background-position: 50% 50%;
            padding: 2px;
            border-radius: 0.2rem;
            width: 20px;
            height: 20px;
        }
        .submit-sub:hover, .submit-main:hover {
            cursor: pointer;
            filter: brightness(1.1);
        }
        #del {
            background-image: url("../../static/story_5/delete.svg");
            background-color:  rgb(235, 123, 103);
        }
        #edit {
            background-image: url("../../static/story_5/edit.svg");
            background-color:  rgb(226, 197, 101);
        }
        #detail {
            background-image: url("../../static/story_5/detail.svg");
            background-color:  rgb(101, 134, 226);
        }
    </style>
    <title>{{caption}} - Kenta</title>
{% endblock %}
{% block content %}
{% include './navbar.html' %}
<div class="bg">
    <div class="matkul-detail">
        <h3>{{datum.name}}</h3>
        <div style="margin-top: 0.5rem ; display:flex; flex-direction:column;">
            <div style="display:flex; flex-direction:row;">
                <label style="width: 120px;">📖 Lecturer</label>
                <p style="font-size: 1.15rem; line-height:100%; transform:translateY(25%);">{{datum.lecturer}}</p>
            </div>
            <diV style="display:flex; flex-direction:row;">
                <label style="width: 120px;">🏫 Classroom</label>
                <p style="font-size: 1.15rem; line-height:100%; transform:translateY(25%);">{{datum.classroom}}</p>
            </diV>
        </div>
        <div style="margin-top: 1rem ;">
            <label>{{datum.sks}} 🕒</label>
            <label>{{datum.get_semester_display}}</label>
            <label>{{datum.get_year_display}}</label>
            {% if datum.difficulty == "?" %}
                <label style="background-color: rgb(189, 151, 226);">
            {% elif datum.difficulty == "1" %}
                <label style="background-color: rgb(100, 197, 137);">
            {% elif datum.difficulty == "2" %}
                <label style="background-color: rgb(226, 214, 101);">
            {% else %}
                <label style="background-color: rgb(235, 123, 103);">
            {% endif %}
            {{datum.get_difficulty_display}}
            </label>
        </div>
        <div style="margin-top: 1rem ;">
            <label style="width: 120px;">📝 Description</label>
            <p style="font-size: 0.8rem; margin:0.5rem 1rem; word-wrap:break-word;">{{datum.desc}}</p>
        </div>
        
        <div style="display:flex;">
            <form action='{% url "story_5:story_5_delete_matkul" datum.id %}' method="POST">
                {% csrf_token %}
                <input id="del" class="submit-main" type="submit" value="">
            </form>
            <a href='{% url "story_5:story_5_edit_matkul" datum.id %}' id="edit" class="submit-sub"></a>
        </div>
    </div>
</div>
{% endblock %}

story_5/templates/story_5/navbar.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="{% static 'story_3/main/css/navbar.css' %}">
    </head>
    <body style="width:100%; height:max-content;">
        <div class="navbar" id="navbar" style="background-color: transparent;">
            <div class="navbar-button-row">
                <a href="/story_5/input" class="navbar-href"><div class="navbar-button"><img src="../../../static/story_5/input.svg">Input</div></a>
                <a href="/story_5/matkul" class="navbar-href"><div class="navbar-button"><img src="../../../static/story_5/matkul.svg">MatKul</div></a>
                <a href="/" class="navbar-href"><div class="navbar-button"><img src="../../../static/story_4/stories.svg">Stories</div></a>
            </div>
        </div>
    </body>
    <script src="../../static/story_3/main/scripts/navbar-scripts.js"></script>
</html>