home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
]

ppw_kenta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story_1/', include('story_1.urls')),
    path('story_2/', include('story_2.urls')),
    path('story_3/', include('story_3.urls')),
    path('story_4/', include('story_4.urls')),
    path('story_5/', include('story_5.urls')),
    path('story_6/', include('story_6.urls')),
    path('story_7/', include('story_7.urls')),
    path('story_8/', include('story_8.urls')),
    path('story_9/', include('story_9.urls')),
]

story_6/urls.py
from django.urls import path

from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.hub, name='story_6'),
    path('add_activity/', views.hub, name='story_6_add_activity'),
    path('delete_activity/<str:pk>', views.delete_activity, name='story_6_delete_activity'),
    path('add_person/', views.hub, name='story_6_add_person'),
    path('delete_person/<str:pk>', views.delete_person, name='story_6_delete_person')
]

story_6/models.py
from django.db import models

class Activity(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)

class Person(models.Model):
    id = models.AutoField(primary_key=True)
    person_name = models.CharField(max_length=30)
    activity = models.ForeignKey(Activity, related_name="people", on_delete=models.CASCADE)

story_6/forms.py
from django import forms
from story_6.models import Activity, Person

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = "__all__"

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = "__all__"

story_6/views.py
from story_6.models import Activity, Person
from django.http import request
from django.shortcuts import redirect, render
from .forms import ActivityForm, PersonForm

context = {}
# Create your views here.
def hub(request):
    context['caption'] = "Story 6"

    if request.method == "POST":
        form = ActivityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/story_6/")

        person_form = PersonForm(request.POST)
        if person_form.is_valid():
            person_form.save()
            return redirect("/story_6/")
    else:
        form = ActivityForm()
        person_form = PersonForm()
    context["activity_form"] = form
    context["person_form"] = person_form

    activities = Activity.objects.all()
    context["activities"] = activities
    return render(request, "story_6/hub.html", context)

def delete_activity(request, pk):
    activity = Activity.objects.get(id=pk)
    if request.method == 'POST':
        activity.delete()
        return redirect('/story_6/')

def delete_person(request, pk):
    person = Person.objects.get(id=pk)
    if request.method == 'POST':
        person.delete()
        return redirect('/story_6/')

story_6/templates/story_6/hub.html
{% extends "navbase.html" %}
{% load static %}
{% block head_overrides %}
    <link rel="stylesheet" href="{% static 'story_6/css/style.css' %}">
    <title>{{caption}} - Kenta</title>
    <style>
    </style>
{% endblock %}
{% block content %}
{% include './navbar.html' %}
<div class="bg">
    <div class="kanban">
        <div class="kanban-board">
            {% if activities %}
                {% for activity in activities %}
                <div class="card">
                    <div class="activity-title">
                        {{activity.name}}
                    </div>
                    {% if activity.people != None %}
                        <div class="people">
                            {% for person in activity.people.all %}
                                <div class="person">
                                    <form class="inline-button-form" action="{% url 'story_6:story_6_delete_person' person.id %}" method="POST">
                                        {% csrf_token %}
                                        <input id="x" class="submit-main" type="submit" value="">
                                    </form>
                                    <div class="person-text">
                                        👤 {{person.person_name}}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <div style="display:flex; flex-direction:row-reverse;">
                        <form action="{% url 'story_6:story_6_delete_activity' activity.id %}" method="POST">
                            {% csrf_token %}
                            <input id="del" class="submit-main" type="submit" value="">
                        </form>
                        <form action="{% url 'story_6:story_6_add_person' %}" method="POST" enctype="multipart/form-data">
                            <div class="input-bar-w-button" style="border: 2px solid #41337A; padding:0.1rem;">
                                {% csrf_token %}
                                {{person_form.person_name}}
                                <input type="hidden" name="activity" value="{{activity.id}}">
                                <input id="add-person" class="submit-main" type="submit" value="">
                            </div>
                        </form>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="activity-input">
        <h2>Make a new activity</h2>
        <form action="" method="POST" enctype="multipart/form-data">
            <div class="input-bar-w-button">
                {% csrf_token %}
                {{activity_form.name}}
                <input id="add" class="submit-main" type="submit" value="">
            </div>
        </form>
    </div>
</div>
{% endblock %}

story_6/templates/story_6/navbar.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="{% static 'story_3/main/css/navbar.css' %}">
    </head>
    <body style="width:100%; height:max-content;">
        <div class="navbar" id="navbar" style="background-color: transparent;">
            <div class="navbar-button-row">
                <a href="/story_6/" class="navbar-href"><div class="navbar-button"><img src="../../../static/story_6/svg/hub.svg">Hub</div></a>
                <a href="/" class="navbar-href"><div class="navbar-button"><img src="../../../static/story_4/stories.svg">Stories</div></a>
            </div>
        </div>
    </body>
    <script src="../../static/story_3/main/scripts/navbar-scripts.js"></script>
</html>